version: '3'

volumes:
  vocabulary_learner_mysql_data: {}
  vocabulary_learner_mysql_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: vocabulary_learner
    container_name: vocabulary_learner 
    depends_on:
      - mysql 
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.mysql
    ports:
      - '8016:8016'
    command: /start

  mysql:
    build:
      context: .
      dockerfile: ./compose/production/mysql/Dockerfile
    image: vocabulary_learner_mysql
    container_name: vocabulary_learner_mysql
    volumes:
      - vocabulary_learner_mysql_data:/var/lib/mysql/data
      - vocabulary_learner_mysql_data_backups:/backups
    env_file:
      - ./.envs/.local/.mysql

