version: '3'

volumes:
  vocabulary_learner_postgres_data: {}
  vocabulary_learner_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: vocabulary_learner
    container_name: vocabulary_learner 
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8016:8016'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: vocabulary_learner_postgres
    container_name: vocabulary_learner_postgres
    volumes:
      - vocabulary_learner_postgres_data:/var/lib/postgresql/data
      - vocabulary_learner_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

