#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset




if [ -z "${MYSQL_USER}" ]; then
    base_postgres_image_default_user='postgres'
    export MYSQL_USER="${base_postgres_image_default_user}"
fi
export DATABASE_URL="postgres://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}"

python << END
import sys
import time

import psycopg

suggest_unrecoverable_after = 30
start = time.time()

while True:
    try:
        psycopg.connect(
            dbname="${MYSQL_DB}",
            user="${MYSQL_USER}",
            password="${MYSQL_PASSWORD}",
            host="${MYSQL_HOST}",
            port="${MYSQL_PORT}",
        )
        break
    except psycopg.OperationalError as error:
        sys.stderr.write("Waiting for MySQL to become available...\n")

        if time.time() - start > suggest_unrecoverable_after:
            sys.stderr.write("  This is taking longer than expected. The following exception may be indicative of an unrecoverable error: '{}'\n".format(error))

    time.sleep(1)
END

>&2 echo 'MySQL is available'

exec "$@"
