# Generated by Django 4.2.5 on 2023-09-15 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conditional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_first_person_singular', models.CharField(max_length=100)),
                ('c_second_person_singular', models.CharField(max_length=100)),
                ('c_third_person_singular', models.CharField(max_length=100)),
                ('c_first_person_plural', models.CharField(max_length=100)),
                ('c_second_person_plural', models.CharField(max_length=100)),
                ('c_third_person_plural', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Future',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_first_person_singular', models.CharField(max_length=100)),
                ('f_second_person_singular', models.CharField(max_length=100)),
                ('f_third_person_singular', models.CharField(max_length=100)),
                ('f_first_person_plural', models.CharField(max_length=100)),
                ('f_second_person_plural', models.CharField(max_length=100)),
                ('f_third_person_plural', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Infinitive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infinitive_form', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True)),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True)),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='PresentPerfect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pp_first_person_singular', models.CharField(max_length=100)),
                ('pp_second_person_singular', models.CharField(max_length=100)),
                ('pp_third_person_singular', models.CharField(max_length=100)),
                ('pp_first_person_plural', models.CharField(max_length=100)),
                ('pp_second_person_plural', models.CharField(max_length=100)),
                ('pp_third_person_plural', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SimplePast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spa_first_person_singular', models.CharField(max_length=100)),
                ('spa_second_person_singular', models.CharField(max_length=100)),
                ('spa_third_person_singular', models.CharField(max_length=100)),
                ('spa_first_person_plural', models.CharField(max_length=100)),
                ('spa_second_person_plural', models.CharField(max_length=100)),
                ('spa_third_person_plural', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SimplePresent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spr_first_person_singular', models.CharField(max_length=100)),
                ('spr_second_person_singular', models.CharField(max_length=100)),
                ('spr_third_person_singular', models.CharField(max_length=100)),
                ('spr_first_person_plural', models.CharField(max_length=100)),
                ('spr_second_person_plural', models.CharField(max_length=100)),
                ('spr_third_person_plural', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TranslationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=50, unique=True)),
                ('created', models.DateField(auto_now_add=True, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Verbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.conditional')),
                ('future', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.future')),
                ('infinitive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.infinitive')),
                ('present_perfect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.presentperfect')),
                ('simple_past', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.simplepast')),
                ('simple_present', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.simplepresent')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.CharField(default='<django.db.models.fields.related.ForeignKey> - <django.db.models.fields.related.ForeignKey>', max_length=203, unique=True)),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('is_a_verb', models.BooleanField(default=False)),
                ('language_a', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vocabulary.languagea')),
                ('language_b', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vocabulary.languageb')),
                ('tenses', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vocabulary.verbs')),
                ('translation_group', models.ManyToManyField(to='vocabulary.translationgroup')),
            ],
        ),
    ]
